/*
 * SPDX-FileCopyrightText: Copyright (c) 2019 NVIDIA CORPORATION & AFFILIATES.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <assert.h>
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <atomic>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "nvbit_tool.h"
#include "nvbit.h"
#include "utils/channel.hpp"
#include "common.h"

#define CHANNEL_SIZE (1L << 20)

// Generated by the Makefile from tool_func/flush_channel.cu.
#include "tool_func/flush_channel.c"

enum class RecvThreadState {
    INIT,
    WORKING,
    STOP,
    FINISHED
};

struct CTXstate {
    ChannelDev *channel_dev = nullptr;
    ChannelHost channel_host;

    CUmodule tool_module;
    CUfunction flush_channel_func;

    std::atomic<RecvThreadState> recv_thread_done{
        RecvThreadState::INIT
    };

    bool need_sync = false;
};

pthread_mutex_t mutex;
pthread_mutex_t cuda_event_mutex;

std::unordered_map<CUcontext, CTXstate *> ctx_state_map;
std::unordered_set<CUfunction> already_instrumented;

bool skip_callback_flag = false;

uint32_t instr_begin_interval = 0;
uint32_t instr_end_interval = UINT32_MAX;
int verbose = 0;

void *recv_thread_fun(void *args);

// ------------------------------------------------------------
// Initial setup: CPU.
// ------------------------------------------------------------

void nvbit_at_init() {
    setenv("CUDA_MANAGED_FORCE_DEVICE_ALLOC", "1", 1);

    GET_VAR_INT(
        instr_begin_interval, "INSTR_BEGIN", 0,
        "Beginning of instruction interval");

    GET_VAR_INT(
        instr_end_interval, "INSTR_END", UINT32_MAX,
        "End of instruction interval");

    GET_VAR_INT(
        verbose, "TOOL_VERBOSE", 0,
        "Enable verbose output");

    pthread_mutexattr_t attr;
    pthread_mutexattr_init(&attr);
    pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);

    pthread_mutex_init(&mutex, &attr);
    pthread_mutex_init(&cuda_event_mutex, &attr);

    pthread_mutexattr_destroy(&attr);
}

// ------------------------------------------------------------
// Instrument each original instruction once: CPU.
// ------------------------------------------------------------

void instrument_function_if_needed(CUcontext ctx, CUfunction func) {
    assert(ctx_state_map.find(ctx) != ctx_state_map.end());
    CTXstate *state = ctx_state_map[ctx];

    std::vector<CUfunction> functions =
        nvbit_get_related_functions(ctx, func);

    functions.push_back(func);

    for (auto f : functions) {
        if (!already_instrumented.insert(f).second) {
            continue;
        }

        const std::vector<Instr *> &instructions =
            nvbit_get_instrs(ctx, f);

        const uint64_t base = nvbit_get_func_addr(ctx, f);
        uint32_t index = 0;

        for (auto instr : instructions) {
            const uint32_t current_index = index++;

            if (current_index < instr_begin_interval ||
                current_index >= instr_end_interval) {
                continue;
            }

            // Original instruction address.
            const uint64_t pc =
                base + (uint64_t)instr->getOffset();

            // instrument_pc(pc, channel_pointer)
            nvbit_insert_call(instr, "instrument_pc", IPOINT_BEFORE);

            nvbit_add_call_arg_const_val64(instr, pc);

            nvbit_add_call_arg_const_val64(
                instr, (uint64_t)state->channel_dev);
        }
    }
}

// ------------------------------------------------------------
// Initialize the GPU-to-CPU channel.
// Called from nvbit_tool_init, not nvbit_at_ctx_init.
// ------------------------------------------------------------

void init_context_state(CUcontext ctx) {
    CTXstate *state = ctx_state_map[ctx];

    state->recv_thread_done.store(RecvThreadState::WORKING);

    CUDA_SAFECALL(
        cudaMallocManaged(&state->channel_dev, sizeof(ChannelDev)));

    state->channel_host.init(
        (int)ctx_state_map.size() - 1,
        CHANNEL_SIZE,
        state->channel_dev,
        recv_thread_fun,
        ctx);

    nvbit_set_tool_pthread(state->channel_host.get_thread());
}

// ------------------------------------------------------------
// Enable instrumentation before a kernel launch.
// ------------------------------------------------------------

static void enter_kernel_launch(CUcontext ctx, CUfunction func) {
    instrument_function_if_needed(ctx, func);
    nvbit_enable_instrumented(ctx, func, true);

    if (verbose) {
        fprintf(
            stderr,
            "PCTRACE: enabling kernel %s\n",
            nvbit_get_func_name(ctx, func));
    }
}

static void leave_kernel_launch(CUcontext ctx, CTXstate *state) {
#ifdef USE_ASYNC_STREAM
    CUDA_SAFECALL(cudaDeviceSynchronize());

    void *args[] = {&state->channel_dev};

    nvbit_launch_kernel(
        ctx, state->flush_channel_func,
        1, 1, 1,
        1, 1, 1,
        0, nullptr, args, nullptr);

    CUDA_SAFECALL(cudaDeviceSynchronize());
#endif
}

// ------------------------------------------------------------
// CUDA API callback: CPU.
// ------------------------------------------------------------

void nvbit_at_cuda_event(
    CUcontext ctx,
    int is_exit,
    nvbit_api_cuda_t cbid,
    const char *name,
    void *params,
    CUresult *pStatus) {

    pthread_mutex_lock(&cuda_event_mutex);

    if (skip_callback_flag) {
        pthread_mutex_unlock(&cuda_event_mutex);
        return;
    }

    skip_callback_flag = true;

    auto entry = ctx_state_map.find(ctx);
    if (entry == ctx_state_map.end()) {
        skip_callback_flag = false;
        pthread_mutex_unlock(&cuda_event_mutex);
        return;
    }

    CTXstate *state = entry->second;

    switch (cbid) {
        case API_CUDA_cuLaunch:
        case API_CUDA_cuLaunchGrid: {
            auto *p = (cuLaunch_params *)params;

            if (!is_exit) {
                state->need_sync = true;
                enter_kernel_launch(ctx, p->f);
            } else {
                leave_kernel_launch(ctx, state);
            }
            break;
        }

        case API_CUDA_cuLaunchKernel:
        case API_CUDA_cuLaunchKernel_ptsz:
        case API_CUDA_cuLaunchCooperativeKernel:
        case API_CUDA_cuLaunchCooperativeKernel_ptsz:
        case API_CUDA_cuLaunchKernelEx:
        case API_CUDA_cuLaunchKernelEx_ptsz:
        case API_CUDA_cuLaunchGridAsync: {
            CUfunction func;
            CUstream stream;

            if (cbid == API_CUDA_cuLaunchKernelEx ||
                cbid == API_CUDA_cuLaunchKernelEx_ptsz) {
                auto *p = (cuLaunchKernelEx_params *)params;
                func = p->f;
                stream = p->config->hStream;
            } else if (cbid == API_CUDA_cuLaunchGridAsync) {
                auto *p = (cuLaunchGridAsync_params *)params;
                func = p->f;
                stream = p->hStream;
            } else {
                auto *p = (cuLaunchKernel_params *)params;
                func = p->f;
                stream = p->hStream;
            }

            cudaStreamCaptureStatus capture_status;

            CUDA_SAFECALL(
                cudaStreamIsCapturing(stream, &capture_status));

            if (!is_exit) {
                state->need_sync = true;
                enter_kernel_launch(ctx, func);
            } else if (capture_status != cudaStreamCaptureStatusActive) {
                leave_kernel_launch(ctx, state);
            }

            break;
        }

        case API_CUDA_cuGraphAddKernelNode: {
            auto *p = (cuGraphAddKernelNode_params *)params;

            if (!is_exit) {
                state->need_sync = true;
                enter_kernel_launch(ctx, p->nodeParams->func);
            }

            break;
        }

        default:
            break;
    }

    skip_callback_flag = false;
    pthread_mutex_unlock(&cuda_event_mutex);
}

// ------------------------------------------------------------
// Receive PC records and write them to stdout: CPU thread.
// ------------------------------------------------------------

void *recv_thread_fun(void *args) {
    CUcontext ctx = (CUcontext)args;

    pthread_mutex_lock(&mutex);

    assert(ctx_state_map.find(ctx) != ctx_state_map.end());
    CTXstate *state = ctx_state_map[ctx];
    ChannelHost *channel = &state->channel_host;

    pthread_mutex_unlock(&mutex);

    char *buffer = (char *)malloc(CHANNEL_SIZE);
    assert(buffer != nullptr);

    uint64_t records = 0;

    while (true) {
        const bool stopping =
            state->recv_thread_done.load() != RecvThreadState::WORKING;

        const uint32_t bytes = channel->recv(buffer, CHANNEL_SIZE);

        if (bytes == 0) {
            if (stopping) {
                break;
            }
            continue;
        }

        assert(bytes % sizeof(pc_access_t) == 0);

        for (uint32_t pos = 0;
             pos < bytes;
             pos += sizeof(pc_access_t)) {

            const pc_access_t *record =
                (const pc_access_t *)(buffer + pos);

            if (printf(
                    "PC 0x%016llx\n",
                    (unsigned long long)record->pc) < 0) {
                perror("PC trace write failed");
                abort();
            }

            records++;
        }
    }

    if (fflush(stdout) != 0) {
        perror("PC trace flush failed");
        abort();
    }

    fprintf(
        stderr,
        "PCTRACE: received %llu warp-instruction records\n",
        (unsigned long long)records);

    free(buffer);

    state->recv_thread_done.store(RecvThreadState::FINISHED);
    return nullptr;
}

// ------------------------------------------------------------
// Context creation: load the flush helper.
// ------------------------------------------------------------

void nvbit_at_ctx_init(CUcontext ctx) {
    pthread_mutex_lock(&mutex);

    assert(ctx_state_map.find(ctx) == ctx_state_map.end());

    CTXstate *state = new CTXstate;
    ctx_state_map[ctx] = state;

    nvbit_load_tool_module(
        ctx,
        (const void *)flush_channel_bin,
        &state->tool_module);

    nvbit_find_function_by_name(
        ctx,
        state->tool_module,
        "flush_channel",
        &state->flush_channel_func);

    pthread_mutex_unlock(&mutex);
}

// ------------------------------------------------------------
// Safe place to allocate the channel.
// ------------------------------------------------------------

void nvbit_tool_init(CUcontext ctx) {
    pthread_mutex_lock(&mutex);

    assert(ctx_state_map.find(ctx) != ctx_state_map.end());
    init_context_state(ctx);

    pthread_mutex_unlock(&mutex);
}

// ------------------------------------------------------------
// Context shutdown: flush, drain, then free.
// ------------------------------------------------------------

void nvbit_at_ctx_term(CUcontext ctx) {
    pthread_mutex_lock(&mutex);
    skip_callback_flag = true;

    assert(ctx_state_map.find(ctx) != ctx_state_map.end());
    CTXstate *state = ctx_state_map[ctx];

    if (state->need_sync) {
        // Finish application kernels before flushing the final records.
        CUDA_SAFECALL(cudaDeviceSynchronize());

        void *args[] = {&state->channel_dev};

        nvbit_launch_kernel(
            ctx, state->flush_channel_func,
            1, 1, 1,
            1, 1, 1,
            0, nullptr, args, nullptr);

        CUDA_SAFECALL(cudaDeviceSynchronize());
    }

    if (state->recv_thread_done.load() != RecvThreadState::INIT) {
        state->recv_thread_done.store(RecvThreadState::STOP);

        while (state->recv_thread_done.load() !=
               RecvThreadState::FINISHED) {
            // Receiver drains the remaining records.
        }

        state->channel_host.destroy(false);
        CUDA_SAFECALL(cudaFree(state->channel_dev));
    }

    delete state;
    ctx_state_map.erase(ctx);

    skip_callback_flag = false;
    pthread_mutex_unlock(&mutex);
}